const express=require("express"),path=require("path"),helmet=require("helmet"),morgan=require("morgan"),Database=require("better-sqlite3");
const app=express(),db=new Database(process.env.DB_FILE||"allworldbrands.db"),PORT=process.env.PORT||3000;
db.pragma("journal_mode=WAL");
db.exec(`CREATE TABLE IF NOT EXISTS countries(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,code TEXT UNIQUE NOT NULL);
CREATE TABLE IF NOT EXISTS brands(id INTEGER PRIMARY KEY AUTOINCREMENT,country_id INTEGER NOT NULL,name TEXT NOT NULL,category TEXT,description TEXT,website TEXT,verification TEXT DEFAULT 'Unverified');
CREATE TABLE IF NOT EXISTS factories(id INTEGER PRIMARY KEY AUTOINCREMENT,brand_id INTEGER NOT NULL,name TEXT NOT NULL,country TEXT,address TEXT,source TEXT);
CREATE TABLE IF NOT EXISTS applications(id INTEGER PRIMARY KEY AUTOINCREMENT,brand_name TEXT NOT NULL,country TEXT NOT NULL,owner_email TEXT NOT NULL,website TEXT,package TEXT DEFAULT 'Basic',status TEXT DEFAULT 'pending',created_at TEXT DEFAULT CURRENT_TIMESTAMP);`);
const cs=[["United States","US"],["United Kingdom","GB"],["Germany","DE"],["France","FR"],["Italy","IT"],["Spain","ES"],["Türkiye","TR"],["Uzbekistan","UZ"],["Japan","JP"],["South Korea","KR"],["China","CN"],["India","IN"],["UAE","AE"],["Saudi Arabia","SA"],["Canada","CA"],["Australia","AU"],["Brazil","BR"],["Mexico","MX"],["Netherlands","NL"],["Switzerland","CH"],["Sweden","SE"],["Norway","NO"],["Poland","PL"],["Singapore","SG"],["Indonesia","ID"]];
const ic=db.prepare("INSERT OR IGNORE INTO countries(name,code) VALUES(?,?)");cs.forEach(x=>ic.run(...x));
if(!db.prepare("SELECT 1 FROM brands LIMIT 1").get()){const gid=db.prepare("SELECT id FROM countries WHERE code=?"),ib=db.prepare("INSERT INTO brands(country_id,name,category,description,website,verification) VALUES(?,?,?,?,?,?)");[
["US","Apple","Electronics","Technology brand profile.","https://www.apple.com","Official source"],["US","Nike","Sports","Sportswear and footwear brand profile.","https://www.nike.com","Official source"],["GB","Burberry","Luxury","British luxury fashion brand profile.","https://www.burberry.com","Official source"],["DE","BMW","Automotive","Automotive brand profile.","https://www.bmw.com","Official source"],["FR","L'Oréal","Cosmetics","Beauty brand profile.","https://www.loreal.com","Official source"],["IT","Ferrari","Automotive","Automotive brand profile.","https://www.ferrari.com","Official source"],["TR","Arçelik","Home","Home appliances brand profile.","https://www.arcelik.com.tr","Official source"],["UZ","Artel","Electronics","Consumer electronics brand profile.","https://artelelectronics.com","Brand provided"],["JP","Toyota","Automotive","Automotive brand profile.","https://global.toyota","Official source"],["KR","Samsung","Electronics","Technology brand profile.","https://www.samsung.com","Official source"],["CN","Huawei","Electronics","Technology brand profile.","https://www.huawei.com","Official source"],["IN","Tata","Industrial","Business group profile.","https://www.tata.com","Official source"]].forEach(x=>ib.run(gid.get(x[0]).id,...x.slice(1)));}
app.use(helmet({contentSecurityPolicy:false}));app.use(morgan("tiny"));app.use(express.json());app.use(express.static(path.join(__dirname,"public")));
app.get("/api/health",(q,r)=>r.json({ok:true,service:"ALL WORLD BRANDS API"}));
app.get("/api/countries",(q,r)=>r.json(db.prepare("SELECT * FROM countries ORDER BY name").all()));
app.get("/api/countries/:id/brands",(q,r)=>r.json(db.prepare("SELECT * FROM brands WHERE country_id=? ORDER BY name").all(q.params.id)));
app.get("/api/brands/:id",(q,r)=>{let b=db.prepare("SELECT b.*,c.name country FROM brands b JOIN countries c ON c.id=b.country_id WHERE b.id=?").get(q.params.id);if(!b)return r.status(404).json({error:"Brand not found"});b.factories=db.prepare("SELECT * FROM factories WHERE brand_id=?").all(q.params.id);r.json(b)});
app.get("/api/search",(q,r)=>{let s=`%${q.query.q||""}%`;r.json(db.prepare("SELECT b.id,b.name,b.category,c.name country,b.verification FROM brands b JOIN countries c ON c.id=b.country_id WHERE b.name LIKE ? OR b.category LIKE ? OR c.name LIKE ? LIMIT 50").all(s,s,s))});
app.post("/api/applications",(q,r)=>{let x=q.body||{};if(!x.brand_name||!x.country||!x.owner_email)return r.status(400).json({error:"Required fields missing"});let i=db.prepare("INSERT INTO applications(brand_name,country,owner_email,website,package) VALUES(?,?,?,?,?)").run(x.brand_name,x.country,x.owner_email,x.website||"",x.package||"Basic");r.status(201).json({id:i.lastInsertRowid,status:"pending"})});
app.get("/api/admin/applications",(q,r)=>r.json(db.prepare("SELECT * FROM applications ORDER BY created_at DESC").all()));
app.get("*",(q,r)=>r.sendFile(path.join(__dirname,"public","index.html")));app.listen(PORT,()=>console.log("ALL WORLD BRANDS: http://localhost:"+PORT));